title: Ita Udotong, MNIS # your name (or website title) here
logo: "https://github.com/itaudotong/udotong6953.github.io/blob/master/ITA%20UDOTONG.jpg?raw=true" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Chief Executive Officer of L'xx On Consult Int. Ltd
  
  <br><br>
  <a href="https://www.linkedin.com/in/ita-udotong-mnis-7329123a/">View My Linkedin Profile</a>
  
  <br><br>
  <a href="https://storymaps.arcgis.com/stories/f3349a3e1c574e92bd5687b9c53f5a7a">View SNAP Distribution in ArcGIS Storymap</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
